#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Apr 01, 2023 04:30:44 PM IST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import tkinter.messagebox as tkMessageBox

import mysql.connector

import dbs

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = dbs.Toplevel1(_top1)
    # # Creates a toplevel widget.
    # global _top2, _w2
    # _top2 = tk.Toplevel(root)
    # _w2 = dbs.Toplevel2(_top2)
    # # Creates a toplevel widget.
    # global _top5, _w5
    # _top5 = tk.Toplevel(root)
    # _w5 = dbs.Toplevel5(_top5)
    # # Creates a toplevel widget.
    # global _top7, _w7
    # _top7 = tk.Toplevel(root)
    # _w7 = dbs.Toplevel5_1(_top7)
    # # Creates a toplevel widget.
    # global _top8, _w8
    # _top8 = tk.Toplevel(root)
    # _w8 = dbs.Toplevel5_2(_top8)
    # # Creates a toplevel widget.
    # global _top9, _w9
    # _top9 = tk.Toplevel(root)
    # _w9 = dbs.Toplevel5_3(_top9)
    # # Creates a toplevel widget.
    # global _top10, _w10
    # _top10 = tk.Toplevel(root)
    # _w10 = dbs.Toplevel3(_top10)
    # # Creates a toplevel widget.
    # global _top12, _w12
    # _top12 = tk.Toplevel(root)
    # _w12 = dbs.Toplevel5_4(_top12)
    try:
                global connc
                connc = mysql.connector.connect(host='localhost',port=3306, database='fest_database3',user='root', password='samyakjain',  auth_plugin='mysql_native_password')
                global cursor
                cursor = connc.cursor()

    except Exception:
                tkMessageBox.showerror("Error", "Database not found")
                sys.exit()
                
    root.mainloop()

if __name__ == '__main__':
    dbs.start_up()




